name: aluupvc_pro
description: AluUPVC Pro
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.14.0

flutter:
  uses-material-design: true
